---

- name: chrony
  tags: chrony
  block:
    - name: Package
      ansible.builtin.apt:
        state: present
        name:
          - chrony

    - name: Service
      ansible.builtin.systemd:
        name: chrony
        state: started
        enabled: true

    - name: Configfile
      ansible.builtin.copy:
        src: chrony.conf
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart chrony
